### ISSUE TITLE
Error Installing xoutil in python 3.4

### ISSUE THREAD

**Issue by edelvalle** [merchise/xotl.tools#1]
I gest this error while installing xoutil 1.7.1 in python 3.4.3 in ubuntu 14.04.

```
Downloading/unpacking xoutil
  Running setup.py (path:/home/docker/venv/build/xoutil/setup.py) egg_info for package xoutil
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/docker/venv/build/xoutil/setup.py", line 23, in <module>
        execfile(release)
      File "/home/docker/venv/build/xoutil/setup.py", line 15, in execfile
        code = compile(f.read(), filename, 'exec')
      File "/home/docker/venv/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 350: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/docker/venv/build/xoutil/setup.py", line 23, in <module>

    execfile(release)

  File "/home/docker/venv/build/xoutil/setup.py", line 15, in execfile

    code = compile(f.read(), filename, 'exec')

  File "/home/docker/venv/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 350: ordinal not in range(128)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/docker/venv/build/xoutil
```

**Comment by edelvalle** [comment]
lol, this is the problem:

When installing xoutil in a docker image it uses the locale of the system to decode the `release.py` file.

And this locales are not set by default; this has to be done before installing anything:

```
# Set the locale
RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8     
```

Sorry @mvaled 
Hugs, Eddy

**Comment by mvaled** [comment]
`setup.py` should work...  I'm reopening the issue.

**Comment by mvaled** [comment]
Well.  I'm closing this issue because the current preferred way to install xotl.tools is wheels.
